### ISSUE TITLE
Dashes in filename causing server error

### ISSUE THREAD

**Issue by jwrudzin** [doublesecretagency/craft-digitaldownload#10]
We recently had a user upload a file that had multiple types of dashes in the name, like '-–'. The filename had both short dashes and long (em) dashes. This resulted in the URL the Digital Download plugin created throwing a 500 error with the message "The file you are looking for does not exist."

The asset is working properly in the CMS, but the Digital Download URL is not working. I could be wrong, but this leads me to believe this is an issue with the plugin rather than a server setting or similar.

Let me know if there's any additional information I can provide!

**Comment by lindseydiloreto** [comment]
Hi there, thanks for reporting!

I just tried doing a few quick tests with a file containing those dashes (-–) in the filename, copy & pasted from your example. From my tests, it looks like everything is working normally.

When I uploaded the file, the extra em dash was stripped out. However, I believe that's because I have [`convertFilenamesToAscii`](https://craftcms.com/docs/3.x/config/config-settings.html#convertfilenamestoascii) set to `true`. So I manually added the file to my assets folder, and "Update[d] asset indexes". Once the file was properly indexed (with the em dash still in the filename), I set up a download link with the [generic example](https://plugins.doublesecretagency.com/digital-download/displaying-a-link/#automatic-token-generation) from the docs.

Everything worked normally for me. The file was downloaded, with the em dash still intact in the filename.

If you can trace the issue back to the plugin, I'd love to get a bit more information! Without digging too deep, there's a chance it's dependant on a subtle variation in that particular server environment (ie: Windows vs Linux, case-sensitive vs not, UTF-8 vs something else, etc). It could be a weird and windy road if you want to investigate further.

You may want to consider just setting [`convertFilenamesToAscii`](https://craftcms.com/docs/3.x/config/config-settings.html#convertfilenamestoascii) to `true`, which should prevent anyone from getting into a similar situation in the future.
